import type { Exercise, WorkoutTemplate, MovementPattern, ExerciseType } from '@/types'

const slugify = (str: string) => str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')

// ─── Seeded Exercises Creator ────────────────────────────────────────────────

const mkEx = (
  name: string,
  category: Exercise['category'],
  muscleGroups: string[],
  equipment?: string,
  aliases?: string[],
  movementPattern?: MovementPattern,
  exerciseType?: ExerciseType
): Exercise => ({
  id: 'ex-' + slugify(name),
  name,
  category,
  muscleGroups,
  equipment,
  isCustom: false,
  aliases,
  movementPattern,
  exerciseType,
})

export const SEEDED_EXERCISES: Exercise[] = [
  // ─── Chest (Movement Patterns: horizontal_push, isolation) ─────────────────
  mkEx('Bench Press', 'strength', ['Chest', 'Triceps', 'Front Delts'], 'Barbell', ['flat bench press', 'barbell bench press', 'bp'], 'horizontal_push', 'compound'),
  mkEx('Incline Bench Press', 'strength', ['Upper Chest', 'Triceps', 'Front Delts'], 'Barbell', ['incline press', 'barbell incline press'], 'horizontal_push', 'compound'),
  mkEx('Decline Bench Press', 'strength', ['Lower Chest', 'Triceps'], 'Barbell', ['decline press', 'barbell decline press'], 'horizontal_push', 'compound'),
  mkEx('Dumbbell Fly', 'strength', ['Chest'], 'Dumbbell', ['db fly', 'chest fly'], 'isolation', 'isolation'),
  mkEx('Incline Dumbbell Fly', 'strength', ['Upper Chest'], 'Dumbbell', ['incline db fly', 'upper chest fly'], 'isolation', 'isolation'),
  mkEx('Decline Dumbbell Fly', 'strength', ['Lower Chest'], 'Dumbbell', ['decline db fly', 'lower chest fly'], 'isolation', 'isolation'),
  mkEx('Dumbbell Press', 'strength', ['Chest', 'Triceps', 'Front Delts'], 'Dumbbell', ['db press', 'flat db press', 'dumbbell bench press', 'db bench'], 'horizontal_push', 'compound'),
  mkEx('Incline Dumbbell Press', 'strength', ['Upper Chest', 'Triceps', 'Front Delts'], 'Dumbbell', ['incline db press', 'upper chest db press', 'incline db press'], 'horizontal_push', 'compound'),
  mkEx('Decline Dumbbell Press', 'strength', ['Lower Chest', 'Triceps'], 'Dumbbell', ['decline db press', 'lower chest db press'], 'horizontal_push', 'compound'),
  mkEx('Cable Fly', 'strength', ['Chest'], 'Cable', ['crossover fly', 'cable crossovers'], 'isolation', 'isolation'),
  mkEx('Low-to-High Cable Fly', 'strength', ['Upper Chest'], 'Cable', ['lower cable fly', 'upper chest cable fly'], 'isolation', 'isolation'),
  mkEx('High-to-Low Cable Fly', 'strength', ['Lower Chest'], 'Cable', ['upper cable fly', 'lower chest cable fly'], 'isolation', 'isolation'),
  mkEx('Dips', 'strength', ['Chest', 'Triceps'], 'Bodyweight', ['chest dips', 'dips chest focus'], 'horizontal_push', 'compound'),
  mkEx('Weighted Dips', 'strength', ['Chest', 'Triceps'], 'Other', ['weighted chest dips', 'dip belt dips'], 'horizontal_push', 'compound'),
  mkEx('Push-Up', 'strength', ['Chest', 'Triceps', 'Core'], 'Bodyweight', ['pushups', 'pushups bodyweight', 'pressups'], 'horizontal_push', 'compound'),
  mkEx('Weighted Push-Up', 'strength', ['Chest', 'Triceps', 'Core'], 'Other', ['weighted pushups'], 'horizontal_push', 'compound'),
  mkEx('Deficit Push-Up', 'strength', ['Chest', 'Triceps', 'Core'], 'Bodyweight', ['deficit pushups'], 'horizontal_push', 'compound'),
  mkEx('Pec Deck', 'strength', ['Chest'], 'Machine', ['chest fly machine', 'machine flyes'], 'isolation', 'isolation'),
  mkEx('Machine Chest Press', 'strength', ['Chest', 'Triceps'], 'Machine', ['chest press machine', 'seated chest press'], 'horizontal_push', 'compound'),
  mkEx('Smith Incline Press', 'strength', ['Upper Chest', 'Triceps'], 'Smith', ['smith machine incline press', 'smith incline bench'], 'horizontal_push', 'compound'),
  mkEx('Smith Machine Bench Press', 'strength', ['Chest', 'Triceps'], 'Smith', ['smith press', 'smith flat bench press'], 'horizontal_push', 'compound'),
  mkEx('Floor Press', 'strength', ['Chest', 'Triceps'], 'Barbell', ['barbell floor press'], 'horizontal_push', 'compound'),
  mkEx('Decline Smith Press', 'strength', ['Lower Chest', 'Triceps'], 'Smith', ['smith decline press', 'smith machine decline bench'], 'horizontal_push', 'compound'),
  mkEx('Hammer Strength Chest Press', 'strength', ['Chest', 'Triceps'], 'Machine', ['hammer chest press', 'machine flat press'], 'horizontal_push', 'compound'),
  mkEx('Hammer Strength Incline Press', 'strength', ['Upper Chest', 'Front Delts'], 'Machine', ['hammer incline press', 'machine incline chest press'], 'horizontal_push', 'compound'),
  mkEx('Hammer Strength Decline Press', 'strength', ['Lower Chest', 'Triceps'], 'Machine', ['hammer decline press', 'machine decline chest press'], 'horizontal_push', 'compound'),
  mkEx('Dumbbell Pull-Over', 'strength', ['Chest', 'Lats', 'Serratus'], 'Dumbbell', ['db pullover', 'pullovers dumbbell'], 'isolation', 'isolation'),
  mkEx('Decline Cable Fly', 'strength', ['Lower Chest'], 'Cable', ['decline crossovers', 'lower chest cable flyes'], 'isolation', 'isolation'),
  mkEx('Single Arm Cable Fly', 'strength', ['Chest'], 'Cable', ['one arm cable fly'], 'isolation', 'isolation'),
  mkEx('Incline Cable Fly', 'strength', ['Upper Chest'], 'Cable', ['incline cable flyes'], 'isolation', 'isolation'),
  mkEx('Incline Chest Press Machine', 'strength', ['Upper Chest', 'Triceps'], 'Machine', ['incline press machine'], 'horizontal_push', 'compound'),
  mkEx('Cable Press', 'strength', ['Chest', 'Triceps'], 'Cable', ['standing cable press'], 'horizontal_push', 'compound'),
  mkEx('Single Arm Dumbbell Press', 'strength', ['Chest', 'Triceps', 'Core'], 'Dumbbell', ['one arm db press'], 'horizontal_push', 'compound'),
  mkEx('Archer Push-Up', 'strength', ['Chest', 'Core', 'Triceps'], 'Bodyweight', ['archer pushups'], 'horizontal_push', 'compound'),
  mkEx('Incline Push-Up', 'strength', ['Lower Chest', 'Triceps'], 'Bodyweight', ['incline pushups'], 'horizontal_push', 'compound'),
  mkEx('Decline Push-Up', 'strength', ['Upper Chest', 'Front Delts'], 'Bodyweight', ['decline pushups'], 'horizontal_push', 'compound'),
  mkEx('Plyometric Push-Up', 'strength', ['Chest', 'Triceps'], 'Bodyweight', ['clapping pushups', 'plyo pushup'], 'horizontal_push', 'compound'),
  mkEx('Dumbbell Floor Press', 'strength', ['Chest', 'Triceps'], 'Dumbbell', ['db floor press'], 'horizontal_push', 'compound'),
  mkEx('Close Grip Dumbbell Press', 'strength', ['Chest', 'Triceps'], 'Dumbbell', ['hex press', 'squeeze press'], 'horizontal_push', 'compound'),

  // ─── Back (Movement Patterns: vertical_pull, horizontal_pull, hinge, isolation)
  mkEx('Deadlift', 'strength', ['Lower Back', 'Glutes', 'Hamstrings', 'Traps'], 'Barbell', ['conventional deadlift', 'dl'], 'hinge', 'compound'),
  mkEx('Sumo Deadlift', 'strength', ['Glutes', 'Quads', 'Hamstrings', 'Lower Back'], 'Barbell', ['sumo dl'], 'hinge', 'compound'),
  mkEx('Romanian Deadlift', 'strength', ['Hamstrings', 'Glutes', 'Lower Back'], 'Barbell', ['rdl', 'barbell rdl'], 'hinge', 'compound'),
  mkEx('Dumbbell Romanian Deadlift', 'strength', ['Hamstrings', 'Glutes', 'Lower Back'], 'Dumbbell', ['db rdl', 'dumbbell rdl'], 'hinge', 'compound'),
  mkEx('Pull-Up', 'strength', ['Lats', 'Biceps', 'Rear Delts'], 'Bodyweight', ['pullups', 'pull up'], 'vertical_pull', 'compound'),
  mkEx('Weighted Pull-Up', 'strength', ['Lats', 'Biceps'], 'Other', ['weighted pullups'], 'vertical_pull', 'compound'),
  mkEx('Chin-Up', 'strength', ['Lats', 'Biceps'], 'Bodyweight', ['chinups', 'chin up'], 'vertical_pull', 'compound'),
  mkEx('Weighted Chin-Up', 'strength', ['Lats', 'Biceps'], 'Other', ['weighted chinups'], 'vertical_pull', 'compound'),
  mkEx('Barbell Row', 'strength', ['Lats', 'Rhomboids', 'Biceps', 'Upper Back'], 'Barbell', ['bent over barbell row', 'bb row'], 'horizontal_pull', 'compound'),
  mkEx('Dumbbell Row', 'strength', ['Lats', 'Rhomboids', 'Biceps'], 'Dumbbell', ['one arm db row', 'single arm dumbbell row', 'db row'], 'horizontal_pull', 'compound'),
  mkEx('Chest Supported Dumbbell Row', 'strength', ['Rhomboids', 'Lats', 'Biceps'], 'Dumbbell', ['chest supported row', 'incline db row'], 'horizontal_pull', 'compound'),
  mkEx('Seated Cable Row', 'strength', ['Lats', 'Rhomboids', 'Biceps'], 'Cable', ['cable row', 'seated row'], 'horizontal_pull', 'compound'),
  mkEx('Lat Pulldown', 'strength', ['Lats', 'Biceps'], 'Cable', ['pulldowns', 'wide grip lat pulldown', 'lat pull down'], 'vertical_pull', 'compound'),
  mkEx('Close Grip Lat Pulldown', 'strength', ['Lats', 'Biceps'], 'Cable', ['close grip pulldown', 'v-bar pulldown'], 'vertical_pull', 'compound'),
  mkEx('Single Arm Lat Pulldown', 'strength', ['Lats', 'Biceps'], 'Cable', ['one arm pulldown', 'one arm lat pulldown'], 'vertical_pull', 'compound'),
  mkEx('T-Bar Row', 'strength', ['Lats', 'Rhomboids', 'Upper Back'], 'Barbell', ['tbar row', 'machine t-bar row'], 'horizontal_pull', 'compound'),
  mkEx('Meadows Row', 'strength', ['Lats', 'Upper Back', 'Rear Delts'], 'Barbell', ['landmine meadows row'], 'horizontal_pull', 'compound'),
  mkEx('Seal Row', 'strength', ['Lats', 'Rhomboids', 'Rear Delts'], 'Barbell', ['barbell seal row', 'flat bench row'], 'horizontal_pull', 'compound'),
  mkEx('Rack Pull', 'strength', ['Lower Back', 'Traps', 'Glutes'], 'Barbell', ['rack pulls'], 'hinge', 'compound'),
  mkEx('Straight Arm Cable Pull-over', 'strength', ['Lats', 'Teres Major'], 'Cable', ['cable pullover', 'straight arm pulldowns'], 'isolation', 'isolation'),
  mkEx('Hyperextension', 'strength', ['Lower Back', 'Hamstrings', 'Glutes'], 'Bodyweight', ['back extension', 'hyperextensions'], 'isolation', 'isolation'),
  mkEx('Weighted Back Extension', 'strength', ['Lower Back', 'Hamstrings', 'Glutes'], 'Other', ['weighted hyperextension'], 'isolation', 'isolation'),
  mkEx('Good Morning', 'strength', ['Hamstrings', 'Glutes', 'Lower Back'], 'Barbell', ['good mornings', 'bb good mornings'], 'hinge', 'compound'),
  mkEx('Chest Supported T-Bar Row', 'strength', ['Rhomboids', 'Lats', 'Biceps'], 'Machine', ['chest supported tbar row'], 'horizontal_pull', 'compound'),
  mkEx('Hammer Strength Row', 'strength', ['Lats', 'Rhomboids', 'Biceps'], 'Machine', ['hammer back row', 'plate loaded row'], 'horizontal_pull', 'compound'),
  mkEx('Hammer Strength High Row', 'strength', ['Lats', 'Upper Back'], 'Machine', ['hammer high row', 'high row machine'], 'horizontal_pull', 'compound'),
  mkEx('Single Arm Lat Row', 'strength', ['Lats', 'Biceps'], 'Machine', ['single arm row machine', 'one arm machine row'], 'horizontal_pull', 'compound'),
  mkEx('Neutral Grip Lat Pulldown', 'strength', ['Lats', 'Biceps'], 'Cable', ['neutral lat pulldown', 'parallel grip pulldown'], 'vertical_pull', 'compound'),
  mkEx('Reverse Grip Lat Pulldown', 'strength', ['Lats', 'Biceps'], 'Cable', ['underhand lat pulldown', 'supinated pulldown'], 'vertical_pull', 'compound'),
  mkEx('Wide Grip Lat Pulldown', 'strength', ['Lats', 'Biceps'], 'Cable', ['wide lat pulldown'], 'vertical_pull', 'compound'),
  mkEx('Cable Lat Pulldown (Single Arm)', 'strength', ['Lats', 'Biceps'], 'Cable', ['one arm cable pulldown'], 'vertical_pull', 'compound'),
  mkEx('One Arm Seated Cable Row', 'strength', ['Lats', 'Rhomboids', 'Biceps'], 'Cable', ['one arm cable row', 'single arm cable row'], 'horizontal_pull', 'compound'),
  mkEx('Cable Pull-through', 'strength', ['Glutes', 'Hamstrings', 'Lower Back'], 'Cable', ['pull throughs cable'], 'hinge', 'compound'),
  mkEx('Deficit Deadlift', 'strength', ['Lower Back', 'Hamstrings', 'Glutes'], 'Barbell', ['deficit dl', 'deficit deadlifts'], 'hinge', 'compound'),
  mkEx('Snatch Grip Deadlift', 'strength', ['Hamstrings', 'Upper Back', 'Lower Back'], 'Barbell', ['snatch dl', 'snatch grip dl'], 'hinge', 'compound'),
  mkEx('Yates Row', 'strength', ['Upper Back', 'Lats', 'Biceps'], 'Barbell', ['underhand barbell row', 'yates barbell row'], 'horizontal_pull', 'compound'),
  mkEx('Incline Dumbbell Row', 'strength', ['Upper Back', 'Rhomboids', 'Biceps'], 'Dumbbell', ['incline db rows', 'prone dumbbell row'], 'horizontal_pull', 'compound'),
  mkEx('Kroc Row', 'strength', ['Lats', 'Upper Back', 'Rhomboids', 'Grip'], 'Dumbbell', ['kroc rows', 'heavy dumbbell row'], 'horizontal_pull', 'compound'),
  mkEx('Lat Pullover Machine', 'strength', ['Lats', 'Serratus'], 'Machine', ['pullover machine', 'nautilus pullover'], 'isolation', 'isolation'),
  mkEx('Pendlay Row', 'strength', ['Lats', 'Upper Back', 'Rhomboids'], 'Barbell', ['pendlay rows', 'strict barbell row'], 'horizontal_pull', 'compound'),
  mkEx('Trap Bar Deadlift', 'strength', ['Quads', 'Glutes', 'Hamstrings', 'Lower Back'], 'Other', ['hex bar deadlift', 'tb dl'], 'hinge', 'compound'),

  // ─── Shoulders (Movement Patterns: vertical_push, isolation) ───────────────
  mkEx('Overhead Press', 'strength', ['Front Delts', 'Triceps', 'Upper Traps'], 'Barbell', ['ohp', 'military press', 'standing overhead press'], 'vertical_push', 'compound'),
  mkEx('Dumbbell Shoulder Press', 'strength', ['Front Delts', 'Triceps'], 'Dumbbell', ['db shoulder press', 'seated db press', 'shoulder press db'], 'vertical_push', 'compound'),
  mkEx('Arnold Press', 'strength', ['Front Delts', 'Side Delts', 'Triceps'], 'Dumbbell', ['arnold shoulder press', 'arnolds'], 'vertical_push', 'compound'),
  mkEx('Seated Barbell Press', 'strength', ['Front Delts', 'Triceps'], 'Barbell', ['seated overhead press', 'seated military press'], 'vertical_push', 'compound'),
  mkEx('Smith Machine Shoulder Press', 'strength', ['Front Delts', 'Triceps'], 'Smith', ['smith ohp', 'smith press shoulder', 'smith press'], 'vertical_push', 'compound'),
  mkEx('Machine Shoulder Press', 'strength', ['Front Delts', 'Triceps'], 'Machine', ['shoulder press machine'], 'vertical_push', 'compound'),
  mkEx('Lateral Raise', 'strength', ['Side Delts'], 'Dumbbell', ['db lateral raise', 'side lateral raise', 'side raises'], 'isolation', 'isolation'),
  mkEx('Cable Lateral Raise', 'strength', ['Side Delts'], 'Cable', ['side raise cable', 'single arm cable side raise'], 'isolation', 'isolation'),
  mkEx('Front Raise', 'strength', ['Front Delts'], 'Dumbbell', ['db front raise', 'front raises'], 'isolation', 'isolation'),
  mkEx('Cable Front Raise', 'strength', ['Front Delts'], 'Cable', ['cable front raises'], 'isolation', 'isolation'),
  mkEx('Upright Row', 'strength', ['Side Delts', 'Traps'], 'Barbell', ['barbell upright row', 'upright rows'], 'isolation', 'isolation'),
  mkEx('Dumbbell Upright Row', 'strength', ['Side Delts', 'Traps'], 'Dumbbell', ['db upright rows'], 'isolation', 'isolation'),
  mkEx('Push Press', 'strength', ['Front Delts', 'Triceps', 'Legs'], 'Barbell', ['push press barbell'], 'vertical_push', 'compound'),
  mkEx('Seated Dumbbell Lateral Raise', 'strength', ['Side Delts'], 'Dumbbell', ['seated lateral raise', 'seated side raise'], 'isolation', 'isolation'),
  mkEx('Incline Dumbbell Lateral Raise', 'strength', ['Side Delts'], 'Dumbbell', ['incline lateral raise', 'leaning dumbbell lateral raise'], 'isolation', 'isolation'),
  mkEx('Behind the Neck Press', 'strength', ['Front Delts', 'Side Delts', 'Triceps'], 'Barbell', ['btn press', 'behind neck press'], 'vertical_push', 'compound'),
  mkEx('Landmine Shoulder Press', 'strength', ['Front Delts', 'Triceps', 'Core'], 'Barbell', ['landmine press', 'single arm landmine shoulder press'], 'vertical_push', 'compound'),
  mkEx('Seated Dumbbell Front Raise', 'strength', ['Front Delts'], 'Dumbbell', ['seated front raise'], 'isolation', 'isolation'),
  mkEx('Cable Lateral Raise (Behind Back)', 'strength', ['Side Delts'], 'Cable', ['behind the back cable lateral raise'], 'isolation', 'isolation'),
  mkEx('Single Arm Dumbbell Shoulder Press', 'strength', ['Front Delts', 'Triceps', 'Core'], 'Dumbbell', ['one arm db shoulder press'], 'vertical_push', 'compound'),
  mkEx('Kettlebell Shoulder Press', 'strength', ['Front Delts', 'Triceps'], 'Other', ['kb press', 'kettlebell shoulder press'], 'vertical_push', 'compound'),
  mkEx('Machine Lateral Raise', 'strength', ['Side Delts'], 'Machine', ['lateral raise machine'], 'isolation', 'isolation'),
  mkEx('Dumbbell Y-Raise', 'strength', ['Side Delts', 'Lower Traps'], 'Dumbbell', ['y raise', 'db y-raise'], 'isolation', 'isolation'),
  mkEx('Cable Face Pull (Lying)', 'strength', ['Rear Delts', 'Upper Back'], 'Cable', ['lying face pull', 'lying cable face pulls'], 'isolation', 'isolation'),
  mkEx('Lying Dumbbell Lateral Raise', 'strength', ['Side Delts'], 'Dumbbell', ['lying side raise', 'side lateral raise lying'], 'isolation', 'isolation'),
  mkEx('Seated Lateral Raise (Machine)', 'strength', ['Side Delts'], 'Machine', ['seated side raise machine'], 'isolation', 'isolation'),

  // ─── Rear Delts (Shoulders Subcategory) ────────────────────────────────────
  mkEx('Face Pull', 'strength', ['Rear Delts', 'Rotator Cuff', 'Upper Back'], 'Cable', ['cable face pull', 'facepulls'], 'isolation', 'isolation'),
  mkEx('Cable Rear Delt Fly', 'strength', ['Rear Delts', 'Upper Back'], 'Cable', ['rear delt fly', 'rear delt flyes', 'cable rear delt crossovers', 'rear delt cable fly'], 'isolation', 'isolation'),
  mkEx('Bent Over Rear Delt Raise', 'strength', ['Rear Delts', 'Upper Back'], 'Dumbbell', ['bent over rear delt fly', 'dumbbell rear delt fly', 'rear delt fly'], 'isolation', 'isolation'),
  mkEx('Reverse Pec Deck', 'strength', ['Rear Delts', 'Upper Back'], 'Machine', ['reverse fly machine', 'machine rear delt fly', 'rear delt pec deck'], 'isolation', 'isolation'),
  mkEx('Single Arm Rear Delt Fly', 'strength', ['Rear Delts'], 'Cable', ['single arm cable rear delt fly', 'one arm rear delt fly'], 'isolation', 'isolation'),
  mkEx('Dumbbell Rear Delt Row', 'strength', ['Rear Delts', 'Upper Back'], 'Dumbbell', ['db rear delt row', 'dumbbell rear delt rows'], 'horizontal_pull', 'compound'),
  mkEx('Cable Rear Delt Row', 'strength', ['Rear Delts', 'Upper Back'], 'Cable', ['cable rear delt rows'], 'horizontal_pull', 'compound'),
  mkEx('Incline Dumbbell Rear Delt Raise', 'strength', ['Rear Delts'], 'Dumbbell', ['incline rear delt raise', 'chest supported rear delt fly'], 'isolation', 'isolation'),

  // ─── Traps (Shoulders Subcategory) ─────────────────────────────────────────
  mkEx('Shrug', 'strength', ['Traps'], 'Barbell', ['barbell shrug', 'shrugs'], 'isolation', 'isolation'),
  mkEx('Barbell Shrug', 'strength', ['Traps'], 'Barbell', ['bb shrug', 'shrugs barbell'], 'isolation', 'isolation'),
  mkEx('Dumbbell Shrug', 'strength', ['Traps'], 'Dumbbell', ['db shrug', 'shrugs dumbbell'], 'isolation', 'isolation'),
  mkEx('Smith Machine Shrug', 'strength', ['Traps'], 'Smith', ['smith shrug', 'smith shrugs'], 'isolation', 'isolation'),
  mkEx('Machine Shrug', 'strength', ['Traps'], 'Machine', ['seated machine shrug', 'shrug machine'], 'isolation', 'isolation'),
  mkEx('Behind Back Barbell Shrug', 'strength', ['Traps'], 'Barbell', ['behind the back shrug', 'lee haney shrug'], 'isolation', 'isolation'),
  mkEx('Trap Bar Farmer Carry', 'strength', ['Traps', 'Forearms', 'Core'], 'Other', ['hex bar carry', 'trap bar farmer walks'], 'cardio', 'compound'),
  mkEx('Dumbbell Farmer Walk', 'strength', ['Traps', 'Forearms', 'Core'], 'Dumbbell', ['db farmer carry', 'db farmer walks'], 'cardio', 'compound'),
  mkEx('Cable Shrug', 'strength', ['Traps'], 'Cable', ['cable shrugs'], 'isolation', 'isolation'),
  mkEx('Overhead Barbell Shrug', 'strength', ['Traps', 'Shoulders'], 'Barbell', ['oh shrug', 'overhead shrugs'], 'isolation', 'isolation'),
  mkEx('Hise Shrug', 'strength', ['Traps', 'Calves'], 'Barbell', ['hise shrugs barbell'], 'isolation', 'isolation'),

  // ─── Arms - Biceps & Forearms (Movement Patterns: isolation) ────────────────
  mkEx('Barbell Curl', 'strength', ['Biceps'], 'Barbell', ['bb curl', 'barbell curls'], 'isolation', 'isolation'),
  mkEx('Dumbbell Curl', 'strength', ['Biceps'], 'Dumbbell', ['db curl', 'dumbbell curls', 'db curls'], 'isolation', 'isolation'),
  mkEx('Hammer Curl', 'strength', ['Biceps', 'Brachialis', 'Forearms'], 'Dumbbell', ['db hammer curl', 'hammer curls'], 'isolation', 'isolation'),
  mkEx('EZ Bar Reverse Curl', 'strength', ['Forearms', 'Brachioradialis', 'Biceps'], 'Barbell', ['reverse curl', 'ez bar reverse curl', 'reverse curls', 'reverse barbell curl'], 'isolation', 'isolation'),
  mkEx('Reverse Curl', 'strength', ['Forearms', 'Biceps'], 'Barbell', ['barbell reverse curl'], 'isolation', 'isolation'),
  mkEx('Reverse Dumbbell Curl', 'strength', ['Forearms', 'Biceps'], 'Dumbbell', ['db reverse curl'], 'isolation', 'isolation'),
  mkEx('Barbell Wrist Curl', 'strength', ['Forearms', 'Wrist Flexors'], 'Barbell', ['wrist curl', 'wrist curls barbell'], 'isolation', 'isolation'),
  mkEx('Dumbbell Wrist Curl', 'strength', ['Forearms', 'Wrist Flexors'], 'Dumbbell', ['db wrist curls', 'wrist curl'], 'isolation', 'isolation'),
  mkEx('Barbell Reverse Wrist Curl', 'strength', ['Forearms', 'Wrist Extensors'], 'Barbell', ['reverse wrist curl'], 'isolation', 'isolation'),
  mkEx('Dumbbell Reverse Wrist Curl', 'strength', ['Forearms', 'Wrist Extensors'], 'Dumbbell', ['db reverse wrist curl'], 'isolation', 'isolation'),
  mkEx('Behind Back Barbell Wrist Curl', 'strength', ['Forearms'], 'Barbell', ['behind back wrist curl', 'behind the back wrist curl'], 'isolation', 'isolation'),
  mkEx('Preacher Curl', 'strength', ['Biceps'], 'Barbell', ['ez bar preacher curl', 'preacher curls', 'preacher curl'], 'isolation', 'isolation'),
  mkEx('Incline Dumbbell Curl', 'strength', ['Biceps'], 'Dumbbell', ['incline db curl', 'incline curls'], 'isolation', 'isolation'),
  mkEx('Cable Curl', 'strength', ['Biceps'], 'Cable', ['cable curls'], 'isolation', 'isolation'),
  mkEx('Concentration Curl', 'strength', ['Biceps'], 'Dumbbell', ['concentration curls'], 'isolation', 'isolation'),
  mkEx('Spider Curl', 'strength', ['Biceps'], 'Dumbbell', ['spider curls db', 'barbell spider curl', 'spider curl'], 'isolation', 'isolation'),
  mkEx('Bayesian Curl', 'strength', ['Biceps'], 'Cable', ['bayesian curls', 'cable behind back curl'], 'isolation', 'isolation'),
  mkEx('Zottman Curl', 'strength', ['Biceps', 'Forearms'], 'Dumbbell', ['zottman curls'], 'isolation', 'isolation'),
  mkEx('Machine Bicep Curl', 'strength', ['Biceps'], 'Machine', ['machine curls', 'bicep machine'], 'isolation', 'isolation'),
  mkEx('EZ Bar Curl', 'strength', ['Biceps'], 'Barbell', ['ez bar curls', 'ez bar bicep curl'], 'isolation', 'isolation'),
  mkEx('Incline Hammer Curl', 'strength', ['Biceps', 'Brachialis'], 'Dumbbell', ['incline db hammer curl'], 'isolation', 'isolation'),
  mkEx('Preacher Curl (Dumbbell)', 'strength', ['Biceps'], 'Dumbbell', ['db preacher curl', 'single arm preacher curl'], 'isolation', 'isolation'),
  mkEx('Preacher Curl (EZ Bar)', 'strength', ['Biceps'], 'Barbell', ['preacher curl ez bar'], 'isolation', 'isolation'),
  mkEx('Preacher Curl (Cable)', 'strength', ['Biceps'], 'Cable', ['cable preacher curls'], 'isolation', 'isolation'),
  mkEx('Cable Hammer Curl', 'strength', ['Biceps', 'Forearms'], 'Cable', ['cable rope hammer curl', 'rope hammer curl'], 'isolation', 'isolation'),
  mkEx('Single Arm Cable Curl', 'strength', ['Biceps'], 'Cable', ['one arm cable curl'], 'isolation', 'isolation'),
  mkEx('Spider Curl (EZ Bar)', 'strength', ['Biceps'], 'Barbell', ['ez bar spider curl'], 'isolation', 'isolation'),
  mkEx('Concentration Curl (Cable)', 'strength', ['Biceps'], 'Cable', ['cable concentration curl'], 'isolation', 'isolation'),
  mkEx('Drag Curl (Barbell)', 'strength', ['Biceps', 'Brachialis'], 'Barbell', ['barbell drag curl', 'drag curls'], 'isolation', 'isolation'),
  mkEx('Drag Curl (Dumbbell)', 'strength', ['Biceps', 'Brachialis'], 'Dumbbell', ['db drag curl'], 'isolation', 'isolation'),
  mkEx('Lying Cable Curl', 'strength', ['Biceps'], 'Cable', ['lying high pulley curl', 'lying cable biceps curl'], 'isolation', 'isolation'),
  mkEx('Waiter Curl', 'strength', ['Biceps', 'Brachialis'], 'Dumbbell', ['waiters curl'], 'isolation', 'isolation'),
  mkEx('Kettlebell Bicep Curl', 'strength', ['Biceps', 'Forearms'], 'Other', ['kb curl', 'kb bicep curl'], 'isolation', 'isolation'),

  // ─── Arms - Triceps (Movement Patterns: horizontal_push, isolation) ─────────
  mkEx('Tricep Pushdown', 'strength', ['Triceps'], 'Cable', ['pushdowns', 'rope pushdowns', 'vbar pushdowns'], 'isolation', 'isolation'),
  mkEx('Rope Tricep Pushdown', 'strength', ['Triceps'], 'Cable', ['rope pushdown'], 'isolation', 'isolation'),
  mkEx('Skull Crusher', 'strength', ['Triceps'], 'Barbell', ['ez bar skull crusher', 'lying tricep extension', 'skullcrushers'], 'isolation', 'isolation'),
  mkEx('Close-Grip Bench Press', 'strength', ['Triceps', 'Chest'], 'Barbell', ['cgbp', 'close grip bp'], 'horizontal_push', 'compound'),
  mkEx('Overhead Tricep Extension', 'strength', ['Triceps'], 'Dumbbell', ['db overhead extension', 'seated overhead extension'], 'isolation', 'isolation'),
  mkEx('Cable Overhead Tricep Extension', 'strength', ['Triceps'], 'Cable', ['cable overhead extension', 'overhead cable extensions'], 'isolation', 'isolation'),
  mkEx('JM Press', 'strength', ['Triceps'], 'Barbell', ['jm press barbell'], 'horizontal_push', 'compound'),
  mkEx('Diamond Push-Up', 'strength', ['Triceps', 'Chest'], 'Bodyweight', ['close grip pushups', 'diamond pushups'], 'horizontal_push', 'compound'),
  mkEx('Tricep Kickback', 'strength', ['Triceps'], 'Dumbbell', ['kickbacks', 'db tricep kickback'], 'isolation', 'isolation'),
  mkEx('Cable Kickback', 'strength', ['Triceps'], 'Cable', ['cable tricep kickback'], 'isolation', 'isolation'),
  mkEx('Bench Dip', 'strength', ['Triceps'], 'Bodyweight', ['bench dips'], 'horizontal_push', 'compound'),
  mkEx('Single Arm Cable Pushdown', 'strength', ['Triceps'], 'Cable', ['one arm tricep pushdown', 'single arm pushdown'], 'isolation', 'isolation'),
  mkEx('V-Bar Tricep Pushdown', 'strength', ['Triceps'], 'Cable', ['v-bar pushdown'], 'isolation', 'isolation'),
  mkEx('Straight Bar Tricep Pushdown', 'strength', ['Triceps'], 'Cable', ['straight bar pushdown'], 'isolation', 'isolation'),
  mkEx('Dumbbell Skull Crusher', 'strength', ['Triceps'], 'Dumbbell', ['db skull crusher', 'db skullcrushers'], 'isolation', 'isolation'),
  mkEx('Cable Skull Crusher', 'strength', ['Triceps'], 'Cable', ['cable skull crushers'], 'isolation', 'isolation'),
  mkEx('Seated Machine Tricep Extension', 'strength', ['Triceps'], 'Machine', ['machine tricep extension', 'triceps machine press'], 'isolation', 'isolation'),
  mkEx('Dip Machine', 'strength', ['Triceps', 'Chest'], 'Machine', ['machine dips', 'seated dip machine'], 'horizontal_push', 'compound'),
  mkEx('Floor Press (Close Grip)', 'strength', ['Triceps', 'Chest'], 'Barbell', ['close grip floor press'], 'horizontal_push', 'compound'),
  mkEx('Smith Machine Close Grip Bench Press', 'strength', ['Triceps', 'Chest'], 'Smith', ['smith close grip bench', 'smith cgbp'], 'horizontal_push', 'compound'),
  mkEx('Single Arm Overhead Cable Extension', 'strength', ['Triceps'], 'Cable', ['one arm overhead cable extension'], 'isolation', 'isolation'),
  mkEx('Single Arm Dumbbell Overhead Extension', 'strength', ['Triceps'], 'Dumbbell', ['one arm overhead db extension'], 'isolation', 'isolation'),
  mkEx('Tate Press', 'strength', ['Triceps'], 'Dumbbell', ['tate presses db', 'dumbbell tate press'], 'isolation', 'isolation'),
  mkEx('Katana Extension', 'strength', ['Triceps'], 'Cable', ['katana extensions cable', 'cable katana extension'], 'isolation', 'isolation'),

  // ─── Forearms (Arms Subcategory) ───────────────────────────────────────────
  mkEx('Wrist Roller', 'strength', ['Forearms', 'Wrist Flexors', 'Wrist Extensors'], 'Other', ['wrist roller tool', 'forearm roller'], 'isolation', 'isolation'),
  mkEx('Pronation Exercise', 'strength', ['Forearms', 'Pronator Teres'], 'Cable', ['forearm pronation', 'pronation belt'], 'isolation', 'isolation'),
  mkEx('Supination Exercise', 'strength', ['Forearms', 'Supinator'], 'Dumbbell', ['forearm supination', 'supination dumbbell'], 'isolation', 'isolation'),
  mkEx('Plate Pinch Carry', 'strength', ['Forearms', 'Grip'], 'Other', ['plate pinch walks', 'pinch grip carry'], 'cardio', 'compound'),
  mkEx('Dead Hang', 'strength', ['Forearms', 'Grip', 'Lats'], 'Bodyweight', ['bar dead hang', 'grip strength hang'], 'isolation', 'isolation'),
  mkEx('Single Arm Farmer Carry', 'strength', ['Core', 'Forearms', 'Traps'], 'Dumbbell', ['suitcase carry', 'single arm suitcase carry'], 'cardio', 'compound'),
  mkEx('Radial Deviation Exercise', 'strength', ['Forearms'], 'Dumbbell', ['radial deviation'], 'isolation', 'isolation'),
  mkEx('Ulnar Deviation Exercise', 'strength', ['Forearms'], 'Dumbbell', ['ulnar deviation'], 'isolation', 'isolation'),
  mkEx('Fat Gripz Barbell Curl', 'strength', ['Biceps', 'Forearms', 'Grip'], 'Barbell', ['fat grip curls', 'thick bar bicep curl'], 'isolation', 'isolation'),
  mkEx('Towel Pull-Up', 'strength', ['Lats', 'Forearms', 'Grip'], 'Bodyweight', ['towel pullups', 'towel grip pullup'], 'vertical_pull', 'compound'),

  // ─── Legs (Movement Patterns: squat, hinge, unilateral, isolation) ─────────
  mkEx('Squat', 'strength', ['Quads', 'Glutes', 'Hamstrings'], 'Barbell', ['back squat', 'barbell squat', 'squats'], 'squat', 'compound'),
  mkEx('Front Squat', 'strength', ['Quads', 'Glutes'], 'Barbell', ['front squats', 'barbell front squat'], 'squat', 'compound'),
  mkEx('Leg Press', 'strength', ['Quads', 'Glutes', 'Hamstrings'], 'Machine', ['45 degree leg press', 'legpress'], 'squat', 'compound'),
  mkEx('Hack Squat', 'strength', ['Quads', 'Glutes'], 'Machine', ['hack squats', 'machine hack squat'], 'squat', 'compound'),
  mkEx('Smith Machine Squat', 'strength', ['Quads', 'Glutes'], 'Smith', ['smith squat'], 'squat', 'compound'),
  mkEx('Bulgarian Split Squat', 'strength', ['Quads', 'Glutes'], 'Dumbbell', ['bss', 'bulgarians', 'split squat'], 'unilateral', 'compound'),
  mkEx('Lunges', 'strength', ['Quads', 'Glutes', 'Hamstrings'], 'Bodyweight', ['walking lunges', 'bodyweight lunges'], 'unilateral', 'compound'),
  mkEx('Walking Lunges', 'strength', ['Quads', 'Glutes', 'Hamstrings'], 'Dumbbell', ['db lunges', 'weighted lunges'], 'unilateral', 'compound'),
  mkEx('Reverse Lunges', 'strength', ['Quads', 'Glutes', 'Hamstrings'], 'Dumbbell', ['db reverse lunges'], 'unilateral', 'compound'),
  mkEx('Leg Extension', 'strength', ['Quads'], 'Machine', ['quad extension', 'extensions'], 'isolation', 'isolation'),
  mkEx('Leg Curl', 'strength', ['Hamstrings'], 'Machine', ['lying leg curl', 'hamstring curl'], 'isolation', 'isolation'),
  mkEx('Seated Leg Curl', 'strength', ['Hamstrings'], 'Machine', ['seated hamstring curl'], 'isolation', 'isolation'),
  mkEx('Stiff-Leg Deadlift', 'strength', ['Hamstrings', 'Glutes', 'Lower Back'], 'Barbell', ['sldl', 'stiff legged deadlift'], 'hinge', 'compound'),
  mkEx('Hip Thrust', 'strength', ['Glutes', 'Hamstrings'], 'Barbell', ['barbell hip thrust', 'hip thrusts'], 'hinge', 'compound'),
  mkEx('Glute Bridge', 'strength', ['Glutes'], 'Bodyweight', ['glute bridge bodyweight'], 'isolation', 'isolation'),
  mkEx('Calf Raise', 'strength', ['Calves'], 'Machine', ['standing calf raise', 'calf raises'], 'isolation', 'isolation'),
  mkEx('Seated Calf Raise', 'strength', ['Calves'], 'Machine', ['seated calf raises'], 'isolation', 'isolation'),
  mkEx('Goblet Squat', 'strength', ['Quads', 'Glutes'], 'Dumbbell', ['goblet squats'], 'squat', 'compound'),
  mkEx('Kettlebell Swing', 'strength', ['Hamstrings', 'Glutes', 'Lower Back'], 'Other', ['kb swing', 'kettlebell swings'], 'hinge', 'compound'),
  mkEx('Cable Kickback Glutes', 'strength', ['Glutes'], 'Cable', ['glute kickback', 'cable glute kickbacks'], 'isolation', 'isolation'),
  mkEx('Belt Squat', 'strength', ['Quads', 'Glutes'], 'Machine', ['belt squat machine', 'pit shark squat'], 'squat', 'compound'),
  mkEx('Safety Bar Squat', 'strength', ['Quads', 'Glutes', 'Lower Back'], 'Barbell', ['ssb squat', 'safety squat bar squats'], 'squat', 'compound'),
  mkEx('Zercher Squat', 'strength', ['Quads', 'Glutes', 'Core', 'Upper Back'], 'Barbell', ['zercher squats'], 'squat', 'compound'),
  mkEx('Dumbbell Squat', 'strength', ['Quads', 'Glutes'], 'Dumbbell', ['db squats', 'dumbbell squats'], 'squat', 'compound'),
  mkEx('Dumbbell Step-Up', 'strength', ['Quads', 'Glutes'], 'Dumbbell', ['db step ups', 'step ups'], 'unilateral', 'compound'),
  mkEx('Barbell Step-Up', 'strength', ['Quads', 'Glutes'], 'Barbell', ['barbell step ups'], 'unilateral', 'compound'),
  mkEx('Single Leg Press', 'strength', ['Quads', 'Glutes'], 'Machine', ['one leg leg press', 'single legpress'], 'unilateral', 'compound'),
  mkEx('Single Leg Extension', 'strength', ['Quads'], 'Machine', ['one leg extension', 'single leg extensions'], 'isolation', 'isolation'),
  mkEx('Single Leg Curl', 'strength', ['Hamstrings'], 'Machine', ['one leg curl', 'single leg curls'], 'isolation', 'isolation'),
  mkEx('Single Leg Romanian Deadlift', 'strength', ['Hamstrings', 'Glutes', 'Core'], 'Dumbbell', ['single leg db rdl', 'one leg rdl'], 'unilateral', 'compound'),
  mkEx('Cable Pull-Through', 'strength', ['Glutes', 'Hamstrings'], 'Cable', ['glute pull through', 'cable pullthroughs'], 'hinge', 'compound'),
  mkEx('Frog Pump', 'strength', ['Glutes'], 'Bodyweight', ['frog pumps bodyweight'], 'isolation', 'isolation'),
  mkEx('Standing Calf Raise (Dumbbell)', 'strength', ['Calves'], 'Dumbbell', ['db calf raise', 'db standing calf raises'], 'isolation', 'isolation'),
  mkEx('Calf Press on Leg Press', 'strength', ['Calves'], 'Machine', ['leg press calf raises', 'calf press'], 'isolation', 'isolation'),
  mkEx('Donkey Calf Raise', 'strength', ['Calves'], 'Machine', ['donkey calf raises'], 'isolation', 'isolation'),
  mkEx('Sissy Squat', 'strength', ['Quads'], 'Bodyweight', ['sissy squats bodyweight'], 'squat', 'compound'),
  mkEx('Abductor Machine', 'strength', ['Glutes', 'Outer Thighs'], 'Machine', ['hip abductions', 'abduction machine'], 'isolation', 'isolation'),
  mkEx('Adductor Machine', 'strength', ['Inner Thighs', 'Adductors'], 'Machine', ['hip adductions', 'adductor machine'], 'isolation', 'isolation'),

  // ─── Core & Abs (Movement Patterns: core, isolation) ──────────────────────
  mkEx('Plank', 'strength', ['Core', 'Abs'], 'Bodyweight', ['planks', 'forearm plank'], 'core', 'isolation'),
  mkEx('Crunch', 'strength', ['Abs'], 'Bodyweight', ['crunches', 'ab crunches'], 'core', 'isolation'),
  mkEx('Hanging Leg Raise', 'strength', ['Abs', 'Core'], 'Bodyweight', ['hanging leg raises', 'hlr'], 'core', 'isolation'),
  mkEx('Hanging Knee Raise', 'strength', ['Abs', 'Core'], 'Bodyweight', ['hanging knee raises'], 'core', 'isolation'),
  mkEx('Ab Wheel Rollout', 'strength', ['Abs', 'Core'], 'Bodyweight', ['ab wheel', 'rollouts'], 'core', 'isolation'),
  mkEx('Russian Twist', 'strength', ['Obliques', 'Core'], 'Bodyweight', ['russian twists'], 'core', 'isolation'),
  mkEx('Cable Crunch', 'strength', ['Abs'], 'Cable', ['kneeling cable crunch', 'cable crunches'], 'core', 'isolation'),
  mkEx('Decline Sit-Up', 'strength', ['Abs'], 'Bodyweight', ['decline situp', 'decline crunches'], 'core', 'isolation'),
  mkEx('Toes to Bar', 'strength', ['Abs', 'Core', 'Grip'], 'Bodyweight', ['t2b', 'toes to bar'], 'core', 'compound'),
  mkEx('Side Plank', 'strength', ['Obliques', 'Core'], 'Bodyweight', ['side planks'], 'core', 'isolation'),
  mkEx('Weighted Crunch', 'strength', ['Abs'], 'Dumbbell', ['db crunches', 'weighted crunches'], 'core', 'isolation'),
  mkEx('Pallof Press', 'strength', ['Obliques', 'Core'], 'Cable', ['cable pallof press', 'pallof press'], 'core', 'isolation'),
  mkEx('Dead Bug', 'strength', ['Core', 'Abs'], 'Bodyweight', ['dead bugs', 'deadbug'], 'core', 'isolation'),
  mkEx('Bird Dog', 'strength', ['Core', 'Lower Back'], 'Bodyweight', ['bird dogs', 'birddog'], 'core', 'isolation'),
  mkEx('Cable Woodchopper', 'strength', ['Obliques', 'Core'], 'Cable', ['woodchoppers', 'cable wood chops'], 'core', 'isolation'),
  mkEx('Reverse Crunch', 'strength', ['Abs', 'Lower Abs'], 'Bodyweight', ['reverse crunches'], 'core', 'isolation'),
  mkEx('Dragon Flag', 'strength', ['Abs', 'Core'], 'Bodyweight', ['dragon flags'], 'core', 'isolation'),
  mkEx('L-Sit', 'strength', ['Abs', 'Core', 'Hip Flexors'], 'Bodyweight', ['l sits', 'lsits'], 'core', 'isolation'),
  mkEx('Hollow Body Hold', 'strength', ['Abs', 'Core'], 'Bodyweight', ['hollow body holds', 'hollow hold'], 'core', 'isolation'),
  mkEx('Decline Weighted Sit-Up', 'strength', ['Abs', 'Core'], 'Dumbbell', ['weighted decline situp'], 'core', 'isolation'),

  // ─── Cardio & Endurance (Movement Patterns: cardio) ────────────────────────
  mkEx('Running', 'cardio', ['Legs', 'Cardiovascular'], undefined, ['treadmill running', 'jogging', 'sprints'], 'cardio', 'cardio'),
  mkEx('Cycling', 'cardio', ['Legs', 'Cardiovascular'], undefined, ['spinning', 'stationary bike', 'exercise bike'], 'cardio', 'cardio'),
  mkEx('Rowing', 'cardio', ['Back', 'Legs', 'Cardiovascular'], 'Machine', ['rowing machine', 'ergometer'], 'cardio', 'cardio'),
  mkEx('Jump Rope', 'cardio', ['Cardiovascular', 'Calves'], undefined, ['skipping', 'skipping rope'], 'cardio', 'cardio'),
  mkEx('Stair Climber', 'cardio', ['Glutes', 'Legs', 'Cardiovascular'], 'Machine', ['stairmaster', 'stairs'], 'cardio', 'cardio'),
  mkEx('Elliptical', 'cardio', ['Cardiovascular'], 'Machine', ['elliptical machine', 'cross trainer'], 'cardio', 'cardio'),
  mkEx('HIIT Sprint', 'cardio', ['Cardiovascular', 'Legs'], undefined, ['sprint intervals', 'hiit'], 'cardio', 'cardio'),
  mkEx('Swimming', 'cardio', ['Full Body', 'Cardiovascular'], undefined, ['swim laps', 'swimming freestyle'], 'cardio', 'cardio'),
  mkEx('Walking', 'cardio', ['Legs', 'Cardiovascular'], undefined, ['treadmill walking', 'walking outdoors', 'steps'], 'cardio', 'cardio'),
  mkEx('Treadmill Run', 'cardio', ['Legs', 'Cardiovascular'], 'Machine', ['treadmill running', 'treadmill run'], 'cardio', 'cardio'),
  mkEx('Treadmill Walk', 'cardio', ['Legs', 'Cardiovascular'], 'Machine', ['treadmill walking', 'treadmill walk'], 'cardio', 'cardio'),
  mkEx('Battle Ropes', 'cardio', ['Full Body', 'Cardiovascular'], 'Other', ['battle rope slam', 'ropes slam'], 'cardio', 'cardio'),
  mkEx('Assault Bike', 'cardio', ['Full Body', 'Cardiovascular'], 'Other', ['air bike', 'fan bike'], 'cardio', 'cardio'),
  mkEx('Kettlebell Snatch Cardio', 'cardio', ['Full Body', 'Cardiovascular'], 'Other', ['kb snatch cardio'], 'cardio', 'cardio'),
  mkEx('Burpee', 'cardio', ['Full Body', 'Cardiovascular'], undefined, ['burpees', 'burpee bodyweight'], 'cardio', 'cardio'),
  mkEx('Mountain Climber', 'cardio', ['Core', 'Legs', 'Cardiovascular'], undefined, ['mountain climbers'], 'cardio', 'cardio'),
  mkEx('Jumping Jacks', 'cardio', ['Cardiovascular'], undefined, ['jumping jack bodyweight'], 'cardio', 'cardio'),
  mkEx('Sled Push', 'cardio', ['Legs', 'Cardiovascular'], 'Other', ['prowler push', 'sled pushes'], 'cardio', 'cardio'),
  mkEx('Sled Pull', 'cardio', ['Legs', 'Cardiovascular'], 'Other', ['prowler pull', 'sled pulls'], 'cardio', 'cardio'),
]

// ─── Seeded Workout Templates ────────────────────────────────────────────────

const findEx = (name: string) => SEEDED_EXERCISES.find((e) => e.name === name)!

const mkTemplateEx = (templateSlug: string, exercise: Exercise, order: number, sets: number, reps: string, rest = 120) => ({
  id: `tmpl-ex-${templateSlug}-${slugify(exercise.name)}`,
  templateId: `tmpl-${templateSlug}`,
  exerciseId: exercise.id,
  exercise,
  orderIndex: order,
  targetSets: sets,
  targetReps: reps,
  restSeconds: rest,
})

export const SEEDED_TEMPLATES: WorkoutTemplate[] = [
  {
    id: 'tmpl-push-a',
    name: 'Push A',
    description: 'Chest, shoulders, and triceps — heavy compound focus',
    splitType: 'push',
    createdAt: '2026-06-20T00:00:00.000Z',
    updatedAt: '2026-06-20T00:00:00.000Z',
    exercises: [
      mkTemplateEx('push-a', findEx('Bench Press'), 0, 4, '5-8', 180),
      mkTemplateEx('push-a', findEx('Overhead Press'), 1, 3, '8-12', 120),
      mkTemplateEx('push-a', findEx('Incline Dumbbell Press'), 2, 3, '10-15', 90),
      mkTemplateEx('push-a', findEx('Lateral Raise'), 3, 4, '15-20', 60),
      mkTemplateEx('push-a', findEx('Tricep Pushdown'), 4, 3, '12-15', 60),
      mkTemplateEx('push-a', findEx('Skull Crusher'), 5, 3, '10-12', 60),
    ],
  },
  {
    id: 'tmpl-pull-a',
    name: 'Pull A',
    description: 'Back and biceps — vertical and horizontal pulling',
    splitType: 'pull',
    createdAt: '2026-06-20T00:00:00.000Z',
    updatedAt: '2026-06-20T00:00:00.000Z',
    exercises: [
      mkTemplateEx('pull-a', findEx('Deadlift'), 0, 3, '3-5', 240),
      mkTemplateEx('pull-a', findEx('Pull-Up'), 1, 4, '6-10', 120),
      mkTemplateEx('pull-a', findEx('Barbell Row'), 2, 3, '8-12', 120),
      mkTemplateEx('pull-a', findEx('Seated Cable Row'), 3, 3, '10-15', 90),
      mkTemplateEx('pull-a', findEx('Face Pull'), 4, 3, '15-20', 60),
      mkTemplateEx('pull-a', findEx('Barbell Curl'), 5, 3, '10-12', 60),
      mkTemplateEx('pull-a', findEx('Hammer Curl'), 6, 2, '12-15', 60),
    ],
  },
  {
    id: 'tmpl-legs-a',
    name: 'Legs A',
    description: 'Quads, hamstrings, glutes, and calves',
    splitType: 'legs',
    createdAt: '2026-06-20T00:00:00.000Z',
    updatedAt: '2026-06-20T00:00:00.000Z',
    exercises: [
      mkTemplateEx('legs-a', findEx('Squat'), 0, 4, '5-8', 180),
      mkTemplateEx('legs-a', findEx('Romanian Deadlift'), 1, 3, '10-12', 120),
      mkTemplateEx('legs-a', findEx('Leg Press'), 2, 3, '12-15', 120),
      mkTemplateEx('legs-a', findEx('Leg Curl'), 3, 3, '12-15', 90),
      mkTemplateEx('legs-a', findEx('Leg Extension'), 4, 3, '15-20', 60),
      mkTemplateEx('legs-a', findEx('Calf Raise'), 5, 4, '15-20', 60),
    ],
  },
  {
    id: 'tmpl-upper-body',
    name: 'Upper Body',
    description: 'Full upper body — push and pull combined',
    splitType: 'upper',
    createdAt: '2026-06-20T00:00:00.000Z',
    updatedAt: '2026-06-20T00:00:00.000Z',
    exercises: [
      mkTemplateEx('upper-body', findEx('Bench Press'), 0, 4, '6-10', 120),
      mkTemplateEx('upper-body', findEx('Barbell Row'), 1, 4, '6-10', 120),
      mkTemplateEx('upper-body', findEx('Overhead Press'), 2, 3, '8-12', 90),
      mkTemplateEx('upper-body', findEx('Lat Pulldown'), 3, 3, '10-12', 90),
      mkTemplateEx('upper-body', findEx('Dumbbell Curl'), 4, 3, '12-15', 60),
      mkTemplateEx('upper-body', findEx('Tricep Pushdown'), 5, 3, '12-15', 60),
    ],
  },
  {
    id: 'tmpl-lower-body',
    name: 'Lower Body',
    description: 'Full lower body — compound and isolation movements',
    splitType: 'lower',
    createdAt: '2026-06-20T00:00:00.000Z',
    updatedAt: '2026-06-20T00:00:00.000Z',
    exercises: [
      mkTemplateEx('lower-body', findEx('Squat'), 0, 4, '5-8', 180),
      mkTemplateEx('lower-body', findEx('Hip Thrust'), 1, 3, '10-15', 90),
      mkTemplateEx('lower-body', findEx('Bulgarian Split Squat'), 2, 3, '10-12', 90),
      mkTemplateEx('lower-body', findEx('Leg Curl'), 3, 3, '12-15', 60),
      mkTemplateEx('lower-body', findEx('Calf Raise'), 4, 4, '15-20', 60),
    ],
  },
  {
    id: 'tmpl-full-body',
    name: 'Full Body',
    description: 'Full body workout — perfect for 3x/week training',
    splitType: 'full',
    createdAt: '2026-06-20T00:00:00.000Z',
    updatedAt: '2026-06-20T00:00:00.000Z',
    exercises: [
      mkTemplateEx('full-body', findEx('Squat'), 0, 3, '5-8', 180),
      mkTemplateEx('full-body', findEx('Bench Press'), 1, 3, '8-10', 120),
      mkTemplateEx('full-body', findEx('Barbell Row'), 2, 3, '8-10', 120),
      mkTemplateEx('full-body', findEx('Overhead Press'), 3, 3, '8-12', 90),
      mkTemplateEx('full-body', findEx('Romanian Deadlift'), 4, 3, '10-12', 90),
    ],
  },
]
